### ISSUE TITLE
Conexão com o MongoDb sendo realizada por variável.

### ISSUE THREAD

**Issue by ivnagst** [ivnagst/API-CPF-Validator#19]
Atualmente, a conexão com o banco de dados é realizada no arquivo dbConnect.ts. No entanto, é necessário mudar a forma como a conexão é inicializada, movendo-a para uma função assíncrona.

**Comment by Farenheith** [comment]
O problema, na verdade, não é onde a conexão é feita, mas sim o fato de não haver garantias que a porta http da aplicação começará a ser escutada só depois da conexão estabelecida
