### ISSUE TITLE
Utilizar TypeScript

### ISSUE THREAD

**Issue by Farenheith** [ivnagst/API-CPF-Validator#3]
Configurar e utilizar Typescript no lugar de Javascript no projeto

Além de configurar typescript e trocar os js por ts, também quero que você configure eslint, prettier e editorconfig, para termos um lint automatizado

**Comment by ivnagst** [comment]
Já havia implementado o TS, entretanto, não havia incluido coisas básicas como o .editorconfig.

Ao movimentar os arquivos, inúmeros erros vieram e fiquei algumas horas lendo e relendo para corrigir os alertas.
